#  ___                 ___
# |   \ ___  __ _ ___ / __|__ _ _ __  ___ ___
# | |) / _ \/ _` / -_) (_ / _` | '  \/ -_|_-<
# |___/\___/\__, \___|\___\__,_|_|_|_\___/__/
#           |___/
#
environment:
  redis:
    uri: redis://localhost
